name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Make venv
        run: python -m venv venv

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: cache-${{ hashFiles('requirements.txt', '.github/requirements.txt') }}
          restore-keys: cache-

      - name: Install Dependencies
        run: |
          . ./venv/bin/activate
          pip install -r requirements.txt
          pip install -r .github/requirements.txt

      - name: Lint
        if: ${{ !cancelled() }}
        run: |
          . ./venv/bin/activate
          pylint $(find ./ -name '*.py' | xargs)

      - name: Type check
        if: ${{ !cancelled() }}
        run: |
          . ./venv/bin/activate
          pyright $(find ./ -name '*.py' | xargs)
